# Generated by Django A.B on YYYY-MM-DD HH:MM
from django.db import migrations

def populate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0004_episode_season_tvshow'),
    ]

    operations = [
        migrations.RunPython(populate)
    ]